name: Lua Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  luacheck:
    name: Run Luacheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1"
          luarocksVersion: "3.9.2"

      - name: Install luacheck
        run: luarocks install luacheck

      - name: Run luacheck
        run: luacheck lua
